apiVersion: v1
name: snglsdao.io
description: A Helm chart for Kubernetes
version: 0.1.0
sources:
  - https://github.com/SingularDTV/snglsdao.io
maintainers:
  - name: Stefan Musat
    email: stefan.musat@consensys.net
  - name: Liviu Damian
    email: livu.damian@consensys.net
