# Default values for snglsdao.io.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# rbac:
  # serviceAccountName: default

# environment: stage/production

app:
  name: snglsdao
  component: website
  # domain: Specify at install/upgrade time

image:
  repository: singulardtv.azurecr.io/snglsdao/website
  # tag: Specify at install/upgrade time
  pullPolicy: Always
  pullSecrets: singulardtv-acr

ingress:
  class: snglsdao

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}
